# Generated by Django 4.2.3 on 2023-07-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_organization_profile_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imported_contacts_CSV')),
                ('status', models.CharField(choices=[('Invalid', 'Invalid'), ('In Progress', 'In Progress'), ('Import Failed', 'Import Failed'), ('Import Success', 'Import Success')], default='In Progress', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.profile')),
            ],
        ),
    ]
