# Generated by Django 4.2.3 on 2023-07-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_importedcontact_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedContactErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.TextField()),
                ('imported_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.importedcontact')),
            ],
        ),
    ]
